version: '3.8'

services:
  web:
    image: ghcr.io/dmitry-osin/quake-live-rules:latest
    ports:
      - "80:80"
    volumes:
      # Mount website files
      - ./http_docs:/var/www/html
      # Mount Apache configuration
      - ./.htaccess:/var/www/html/.htaccess
    restart: unless-stopped